import Palash from "../../public/palash.png";

export const teamMembers = [
	{
		name: "Palash Shukla",
		position: "President",
		bio: "narc",
		image: Palash,
		website: "https://palashshukla.me",
		github: "https://github.com/frostbyte8909",
		insta: "https://www.instagram.com/palaaaaaashh/",
		linkedin: "https://www.linkedin.com/in/palash-shukla-neutron",
	},
	{
		name: "Vansh Bhardwaj",
		position: "Consultant",
		bio: "",
		image: "https://placehold.co/400x400",
	},
	{
		name: "Medhansh Kapoor",
		position: "Consultant",
		bio: "",
		image: "https://placehold.co/400x400",
	},
	{
		name: "Position Open",
		position: "Head Editing",
		bio: "",
		image: "https://placehold.co/400x400",
	},
	{
		name: "Position Open",
		position: "Head Development",
		bio: "",
		image: "https://placehold.co/400x400",
	},
	{
		name: "Position Open",
		position: "Head Graphics",
		bio: "",
		image: "https://placehold.co/400x400",
	},
	{
		name: "Position Open",
		position: "Head Gaming",
		bio: "",
		image: "https://placehold.co/400x400",
	},
	{
		name: "Position Open",
		position: "Head AI",
		bio: "",
		image: "https://placehold.co/400x400",
	},
	{
		name: "Position Open",
		position: "Head CyberSecurity",
		bio: "",
		image: "https://placehold.co/400x400",
	},
	{
		name: "Position Open",
		position: "Member",
		bio: "",
		image: "https://placehold.co/400x400",
	},
	{
		name: "Position Open",
		position: "Member",
		bio: "",
		image: "https://placehold.co/400x400",
	},
	{
		name: "Position Open",
		position: "Member",
		bio: "",
		image: "https://placehold.co/400x400",
	},
	{
		name: "Position Open",
		position: "Member",
		bio: "",
		image: "https://placehold.co/400x400",
	},
	{
		name: "Position Open",
		position: "Member",
		bio: "",
		image: "https://placehold.co/400x400",
	},
	{
		name: "Position Open",
		position: "Member",
		bio: "",
		image: "https://placehold.co/400x400",
	},
	{
		name: "Position Open",
		position: "Member",
		bio: "",
		image: "https://placehold.co/400x400",
	},
	{
		name: "Position Open",
		position: "Member",
		bio: "",
		image: "https://placehold.co/400x400",
	},
];
